### PR TITLE
Update index.rst

### PR DESCRIPTION
**Pull request by alexryangregor**
Copyediting complete.

### CODE REVIEW

**Comment by dfguerrerom** [comment]
Hi @alexryangregor , just to confirm. Did you take a look at the rest of the files in the sepal folder? https://github.com/sepal-contrib/wcmc-mgci/tree/main/docs/source/sepal:
```
module_usage.rst
requirements.rst
sources.rst
```

**Comment by alexryangregor** [comment]
> Hi @alexryangregor , just to confirm. Did you take a look at the rest of the files in the sepal folder? https://github.com/sepal-contrib/wcmc-mgci/tree/main/docs/source/sepal:
> 
> ```
> module_usage.rst
> requirements.rst
> sources.rst
> ```

Hi @dfguerrerom, thanks for checking. Yes, I'm working through "Module user interface" and "Module requirements" now. Those are the other files you're referring to, correct?

**Comment by dfguerrerom** [comment]
> > Hi @alexryangregor , just to confirm. Did you take a look at the rest of the files in the sepal folder? https://github.com/sepal-contrib/wcmc-mgci/tree/main/docs/source/sepal:
> > ```
> > module_usage.rst
> > requirements.rst
> > sources.rst
> > ```
> 
> Hi @dfguerrerom, thanks for checking. Yes, I'm working through "Module user interface" and "Module requirements" now. Those are the other files you're referring to, correct?

thank you, are you planning to check them in a different branch/PR? or will you continue in this PR?

**Comment by alexryangregor** [comment]
> > > Hi @alexryangregor , just to confirm. Did you take a look at the rest of the files in the sepal folder? https://github.com/sepal-contrib/wcmc-mgci/tree/main/docs/source/sepal:
> > > ```
> > > module_usage.rst
> > > requirements.rst
> > > sources.rst
> > > ```
> > 
> > 
> > Hi @dfguerrerom, thanks for checking. Yes, I'm working through "Module user interface" and "Module requirements" now. Those are the other files you're referring to, correct?
> 
> thank you, are you planning to check them in a different branch/PR? or will you continue in this PR?

@dfguerrerom You're welcome. I'll probably commit changes and start new PRs, as it's quicker and easier for me. Is that ok with you?

**Comment by alexryangregor** [comment]
Thanks @dfguerrerom. I'll note that for next time!

**Pull request merged**
